[package]
name = "rust-ui-druid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# https://crates.io/crates/druid

[dependencies]
druid = "0.8.3"
